var searchData=
[
  ['scrambledlocalfriendcode_8181',['ScrambledLocalFriendCode',['../namespacenn_1_1uds_1_1Cafe.html#structnn_1_1uds_1_1Cafe_1_1ScrambledLocalFriendCode',1,'nn::uds::Cafe']]],
  ['serializerfromptr_8182',['SerializerFromPtr',['../classnn_1_1sl_1_1details_1_1SerializerFromPtr.html',1,'nn::sl::details']]],
  ['serializerfromptr_3c_20nn_3a_3asl_3a_3akillernotification_20_3e_8183',['SerializerFromPtr&lt; nn::sl::KillerNotification &gt;',['../classnn_1_1sl_1_1details_1_1SerializerFromPtr.html',1,'nn::sl::details']]],
  ['serializerfromptr_3c_20nn_3a_3asl_3a_3atitleinfo_20_3e_8184',['SerializerFromPtr&lt; nn::sl::TitleInfo &gt;',['../classnn_1_1sl_1_1details_1_1SerializerFromPtr.html',1,'nn::sl::details']]],
  ['serializerfromptr_3c_20ostime_20_3e_8185',['SerializerFromPtr&lt; OSTime &gt;',['../classnn_1_1sl_1_1details_1_1SerializerFromPtr.html',1,'nn::sl::details']]],
  ['servent_8186',['servent',['../netdb_8h.html#structservent',1,'']]],
  ['server_8187',['Server',['../classnn_1_1dlp_1_1Cafe_1_1Server.html',1,'nn::dlp::Cafe']]],
  ['serverprivate_8188',['ServerPrivate',['../classnn_1_1dlp_1_1Cafe_1_1ServerPrivate.html',1,'nn::dlp::Cafe']]],
  ['setting_8189',['Setting',['../namespacenn_1_1sl.html#structnn_1_1sl_1_1Setting',1,'nn::sl']]],
  ['setting_2ecaffeine_8190',['Setting.caffeine',['../namespacenn_1_1sl.html#structnn_1_1sl_1_1Setting_8caffeine',1,'nn::sl']]],
  ['settingaccessorfromptr_8191',['SettingAccessorFromPtr',['../classnn_1_1sl_1_1details_1_1SettingAccessorFromPtr.html',1,'nn::sl::details']]],
  ['smdctrltable_8192',['SmdCtrlTable',['../group__coreinit__smd.html#structSmdCtrlTable',1,'']]],
  ['smdelement_8193',['SmdElement',['../group__coreinit__smd.html#structSmdElement',1,'']]],
  ['smdelement_2e_5f_5funnamed13_5f_5f_8194',['SmdElement.__unnamed13__',['../group__coreinit__smd.html#unionSmdElement_8____unnamed13____',1,'']]],
  ['smdinterface_8195',['SmdInterface',['../group__coreinit__smd.html#structSmdInterface',1,'']]],
  ['smdppc_8196',['SmdPpc',['../group__coreinit__smd.html#structSmdPpc',1,'']]],
  ['smdppcctrltablevectors_8197',['SmdPpcCtrlTableVectors',['../group__coreinit__smd.html#structSmdPpcCtrlTableVectors',1,'']]],
  ['smdreceivedata_8198',['SmdReceiveData',['../group__coreinit__smd.html#structSmdReceiveData',1,'']]],
  ['smdreceivedata_2e_5f_5funnamed15_5f_5f_8199',['SmdReceiveData.__unnamed15__',['../group__coreinit__smd.html#unionSmdReceiveData_8____unnamed15____',1,'']]],
  ['smdsimplebufpool_8200',['SmdSimpleBufPool',['../group__coreinit__smd.html#structSmdSimpleBufPool',1,'']]],
  ['smdvector_8201',['SmdVector',['../group__coreinit__smd.html#structSmdVector',1,'']]],
  ['smdvectorspec_8202',['SmdVectorSpec',['../group__coreinit__smd.html#structSmdVectorSpec',1,'']]],
  ['sockaddr_8203',['sockaddr',['../sys_2socket_8h.html#structsockaddr',1,'']]],
  ['sockaddr_5fin_8204',['sockaddr_in',['../in_8h.html#structsockaddr__in',1,'']]],
  ['sockaddr_5fstorage_8205',['sockaddr_storage',['../sys_2socket_8h.html#structsockaddr__storage',1,'']]],
  ['storageinfo_8206',['StorageInfo',['../namespacenn_1_1spm.html#structnn_1_1spm_1_1StorageInfo',1,'nn::spm']]],
  ['storagelistitem_8207',['StorageListItem',['../namespacenn_1_1spm.html#structnn_1_1spm_1_1StorageListItem',1,'nn::spm']]],
  ['sysappbrowserargs_8208',['SysAppBrowserArgs',['../group__sysapp__switch.html#structSysAppBrowserArgs',1,'']]],
  ['sysappbrowserargswithcallback_8209',['SysAppBrowserArgsWithCallback',['../group__sysapp__switch.html#structSysAppBrowserArgsWithCallback',1,'']]],
  ['sysappemanualargs_8210',['SysAppEManualArgs',['../group__sysapp__switch.html#structSysAppEManualArgs',1,'']]],
  ['sysappeshopargs_8211',['SysAppEShopArgs',['../group__sysapp__switch.html#structSysAppEShopArgs',1,'']]],
  ['sysappmiimakerargs_8212',['SysAppMiiMakerArgs',['../group__sysapp__launch.html#structSysAppMiiMakerArgs',1,'']]],
  ['sysappnotificationargs_8213',['SysAppNotificationArgs',['../group__sysapp__launch.html#structSysAppNotificationArgs',1,'']]],
  ['sysappparentalargs_8214',['SysAppParentalArgs',['../group__sysapp__launch.html#structSysAppParentalArgs',1,'']]],
  ['sysappsettingsargs_8215',['SysAppSettingsArgs',['../group__sysapp__launch.html#structSysAppSettingsArgs',1,'']]],
  ['sysargdatablock_8216',['SYSArgDataBlock',['../group__sysapp__args.html#structSYSArgDataBlock',1,'']]],
  ['sysargdatablock_2e_5f_5funnamed51_5f_5f_8217',['SYSArgDataBlock.__unnamed51__',['../group__sysapp__args.html#unionSYSArgDataBlock_8____unnamed51____',1,'']]],
  ['sysargdatablock_2e_5f_5funnamed51_5f_5f_2edata_8218',['SYSArgDataBlock.__unnamed51__.data',['../group__sysapp__args.html#structSYSArgDataBlock_8____unnamed51_____8data',1,'']]],
  ['sysargdatablock_2e_5f_5funnamed51_5f_5f_2estring_8219',['SYSArgDataBlock.__unnamed51__.string',['../group__sysapp__args.html#structSYSArgDataBlock_8____unnamed51_____8string',1,'']]],
  ['syscallerinfo_8220',['SYSCallerInfo',['../group__sysapp__args.html#structSYSCallerInfo',1,'']]],
  ['sysdeserializearg_8221',['SYSDeserializeArg',['../group__sysapp__args.html#structSYSDeserializeArg',1,'']]],
  ['sysstandardargs_8222',['SYSStandardArgs',['../group__sysapp__args.html#structSYSStandardArgs',1,'']]],
  ['sysstandardargsin_8223',['SYSStandardArgsIn',['../group__sysapp__args.html#structSYSStandardArgsIn',1,'']]],
  ['sysstandardargsout_8224',['SYSStandardArgsOut',['../group__sysapp__args.html#structSYSStandardArgsOut',1,'']]]
];
