var searchData=
[
  ['sampler_15945',['Sampler',['../group__gx2__sampler.html',1,'']]],
  ['save_15946',['Save',['../group__nn__acp__save.html',1,'']]],
  ['scheduler_15947',['Scheduler',['../group__coreinit__scheduler.html',1,'']]],
  ['screen_15948',['Screen',['../group__coreinit__screen.html',1,'']]],
  ['semaphore_15949',['Semaphore',['../group__coreinit__semaphore.html',1,'']]],
  ['shaders_15950',['Shaders',['../group__gx2__shader.html',1,'']]],
  ['smd_15951',['SMD',['../group__coreinit__smd.html',1,'']]],
  ['sndcore2_15952',['sndcore2',['../group__sndcore2.html',1,'']]],
  ['socket_15953',['Socket',['../group__nsysnet__socket.html',1,'']]],
  ['software_20keyboard_15954',['Software Keyboard',['../group__nn__swkbd__swkbd.html',1,'']]],
  ['spinlock_15955',['Spinlock',['../group__coreinit__spinlock.html',1,'']]],
  ['state_15956',['State',['../group__gx2__state.html',1,'']]],
  ['surface_15957',['Surface',['../group__gx2__surface.html',1,'(Global Namespace)'],['../group__gx2r__surface.html',1,'(Global Namespace)']]],
  ['swap_15958',['Swap',['../group__gx2__swap.html',1,'']]],
  ['swkbd_15959',['swkbd',['../group__swkbd.html',1,'']]],
  ['synchronization_15960',['Synchronization',['../group__dmae__sync.html',1,'']]],
  ['sysapp_15961',['sysapp',['../group__sysapp.html',1,'']]],
  ['sysapp_20arguments_15962',['SYSAPP Arguments',['../group__sysapp__args.html',1,'']]],
  ['sysapp_20launch_15963',['SYSAPP Launch',['../group__sysapp__launch.html',1,'']]],
  ['sysapp_20switch_15964',['SYSAPP Switch',['../group__sysapp__switch.html',1,'']]],
  ['sysapp_20title_15965',['SYSAPP Title',['../group__sysapp__title.html',1,'']]],
  ['system_20info_15966',['System Info',['../group__coreinit__systeminfo.html',1,'']]]
];
